# Business Rules Configuration
# Defines business logic and calculation rules

locations:
  # Sale locations (Pennsylvania state)
  pennsylvania:
    names: ["Pennsylvania", "Pittsburgh", "West View", "Cranberry", "Cranberry Hearing & Balance Center"]
    state: "Pennsylvania"
    primary: true
    for_sale: true
    description: "Pennsylvania locations for sale (Pittsburgh/West View + Cranberry)"
    
    # Detailed location information for sale locations
    cranberry_location:
      location_id: "cranberry_pa"
      name: "Cranberry Hearing & Balance"
      address: "20820 Route 19, Suite A"
      city: "Cranberry Twp"
      state: "PA"
      zip_code: "16066"
      phone: "724-779-4444"
      google_maps_url: "https://www.google.com/maps/place/20820%20Route%2019+Cranberry%20Twp+PA+16066"
      location_type: "primary"
      for_sale: true
      parking_spaces: 10
      staff_count: 2.5  # 2 dedicated + 0.5 shared staff
      
    west_view_location:
      location_id: "west_view_pa"
      name: "Cranberry Hearing & Balance - West View"
      address: "999 West View Park Drive"
      city: "Pittsburgh"
      state: "PA"
      zip_code: "15229"
      phone: "412-931-9290"
      google_maps_url: "https://www.google.com/maps/place/999%20West%20View%20Park%20Drive+Pittsburgh+PA+15229"
      location_type: "satellite"
      for_sale: true
      parking_spaces: 10
      staff_count: 2.5  # 2 dedicated + 0.5 shared staff
      square_footage: 1500  # West View location square footage
      
  # Non-sale locations (Virginia state)  
  virginia:
    names: ["Virginia", "Annandale", "Alexandria"]
    state: "Virginia"
    primary: false
    for_sale: false  # NOT FOR SALE
    description: "Virginia locations not for sale (Annandale + Alexandria)"
    
staff_categories:
  audiologists: ["Jenna Wickham", "Jordan Zdinak", "Hima Bindu Dasari"]
  technicians: ["Barbara Beck", "Jessica Cooper"]
  support: ["Kristen McCabe", "Richard Hoben"]

# Business operational details
business_details:
  total_employees: 5  # 2 staff per location + 1 shared staff member
  employees_per_location: 2.5  # 2 dedicated + 0.5 shared per location
  shared_employees: 1  # 1 person shared between both locations
  total_locations: 2
  business_hours: "Monday-Friday 9AM-5PM"
  staffing_model: "2 dedicated staff per location + 1 shared staff member"

# Services offered (updated to reflect current offerings - no in-home services)
services:
  hearing_tests:
    - "Diagnostic Audiologic Evaluations"
    - "Diagnostic Hearing Evaluations"
    - "Industrial Hearing Tests"
    - "Tympanometry"
  hearing_aid_services:
    - "Hearing Aid Dispensing and Fitting"
    - "Hearing Aid Evaluation"
    - "Hearing Aid Repair"
  additional_services:
    - "Earwax Removal"
    - "Hearing and Balance Testing"
    - "Tinnitus Treatment and Evaluations"
    - "Custom Earmolds and Earplugs"
    - "Musicians Earplugs and Monitors"
  note: "In-home services are no longer offered - all services are performed at clinic locations"
  
product_categories:
  hearing_aids: ["Hearing Aid", "HA", "Hearing Device"]
  accessories: ["Accessory", "Battery", "Ear Mold"]
  services: ["Service", "Fee", "Consultation"]
  repairs: ["Repair", "Warranty", "Replacement"]
  
financial_metrics:
  ebitda_margin_target: 0.256  # 25.6% target EBITDA margin (from website analysis)
  revenue_growth_target: 0.10  # 10% target annual growth
  transaction_volume_target: 1000  # Monthly transaction target
  
# Equipment configuration (fallback values - actual values calculated dynamically from CSV files)
equipment:
  total_value: 61727  # Fallback value if CSV calculation fails
  description: "Professional audiology equipment including Cello Audiometer, Trumpet REM System, CL12BLP Equipment, Test Booths"
  source: "Fallback from business rules - actual values calculated dynamically from CSV files"
  validation:
    minimum_reasonable_value: 10000  # Minimum reasonable equipment value in dollars
    description: "Equipment values below this threshold are flagged as potentially unreasonable"
  
valuation_multipliers:
  revenue_multiple_min: 0.8
  revenue_multiple_max: 1.2
  ebitda_multiple_min: 3.0
  ebitda_multiple_max: 5.0
  
data_quality:
  min_transaction_amount: 0.01
  max_transaction_amount: 50000.00
  required_fields: ["sale_date", "total_price", "clinic_name", "staff_name"]
  
# Configurable date range for analysis
analysis_period:
  start_date: "2023-01-01"
  end_date: "2025-06-30"  # End of Q2 2025
  description: "Website analysis period: Jan 1, 2023 to end of Q2 2025"
  # Annual projection calculation: (Total Revenue รท Months in Period) ร 12
  # This ensures consistent monthly averages based on the specified date range

# P&L data filtering rules
pnl_filtering:
  # Filter P&L data to only include sale locations (Pennsylvania state)
  include_states: ["Pennsylvania"]
  exclude_states: ["Virginia"]
  description: "P&L data is broken down by state - only include Pennsylvania revenue for sale locations"
  # This ensures we only count revenue from the 2 locations for sale (Pittsburgh/West View + Cranberry)
  # and exclude the 2 locations not for sale (Annandale + Alexandria)
  
# Full data range available
data_range:
  start: "2021-01-01"
  end: "2025-12-31"

# Business sale information
sale_details:
  reason_for_sale: "Owner retirement and lifestyle change"  # Must match standard_reasons
  secondary_reason: "Absentee owner seeking to focus on other ventures"  # Optional additional reason
  sale_type: "Owner retirement and lifestyle transition"
  urgency: "standard"  # Enum: "standard" | "urgent"
  owner_involvement: "absentee"  # Enum: "absentee" | "active" | "partial"
  transition_support: "Available for smooth transition and training period"
  
# Professional reasons for sale (standard business language)
standard_reasons:
  - "Owner retirement and lifestyle change"
  - "Absentee owner seeking to focus on other ventures"
  - "Owner pursuing new opportunities"
  - "Family circumstances requiring sale"
  - "Strategic business decision"
  - "Owner relocation"

# Insurance and payment information
insurance_coverage:
  primary_insurers:
    - name: "UPMC"
      contract_date: "2006-08-31"
      contract_type: "Ancillary Provider Agreement"
      status: "Active"
      coverage_type: "Primary Insurance"
      
    - name: "Aetna"
      contract_date: "2015-09-28"
      contract_type: "Provider Agreement"
      status: "Active"
      coverage_type: "Primary Insurance"
      
  payment_methods:
    - "Insurance billing (UPMC, Aetna)"
    - "Private pay"
    - "Cash payments"
    - "Payment plans available"
    
  billing_system:
    description: "Established insurance billing relationships"
    benefits:
      - "Steady cash flow from insurance payments"
      - "Reduced collection risk"
      - "Professional billing relationships"
      - "Established provider network status"