# Business Rules Configuration
# Defines business logic and calculation rules

locations:
  pittsburgh:
    names: ["Pittsburgh", "West View"]
    primary: true
    for_sale: true
  cranberry:
    names: ["Cranberry Hearing & Balance Center", "Cranberry"]
    primary: false
    for_sale: true
  annandale:
    names: ["Annandale"]
    primary: false
    for_sale: false  # NOT FOR SALE
  alexandria:
    names: ["Alexandria"]
    primary: false
    for_sale: false  # NOT FOR SALE
    
staff_categories:
  audiologists: ["Jenna Wickham", "Jordan Zdinak", "Hima Bindu Dasari"]
  technicians: ["Barbara Beck", "Jessica Cooper"]
  support: ["Kristen McCabe", "Richard Hoben"]
  
product_categories:
  hearing_aids: ["Hearing Aid", "HA", "Hearing Device"]
  accessories: ["Accessory", "Battery", "Ear Mold"]
  services: ["Service", "Fee", "Consultation"]
  repairs: ["Repair", "Warranty", "Replacement"]
  
financial_metrics:
  ebitda_margin_target: 0.169  # 16.9% target EBITDA margin (accounts for taxes, loans, owner compensation, and overhead)
  revenue_growth_target: 0.10  # 10% target annual growth
  transaction_volume_target: 1000  # Monthly transaction target
  
# Configurable equipment value (based on PDF documentation)
equipment:
  total_value: 61728  # Total equipment value from PDF documentation
  description: "Professional audiology equipment including Cello Audiometer, Trumpet REM System, CL12BLP Equipment, AUD System"
  source: "PDF documentation - manually verified"
  
valuation_multipliers:
  revenue_multiple_min: 0.8
  revenue_multiple_max: 1.2
  ebitda_multiple_min: 3.0
  ebitda_multiple_max: 5.0
  
data_quality:
  min_transaction_amount: 0.01
  max_transaction_amount: 50000.00
  required_fields: ["sale_date", "total_price", "clinic_name", "staff_name"]
  
# Configurable date range for analysis
analysis_period:
  start_date: "2023-01-01"
  end_date: "2025-06-30"  # End of Q2 2025
  description: "Website analysis period: Jan 1, 2023 to end of Q2 2025"
  # Annual projection calculation: (Total Revenue รท Months in Period) ร 12
  # This ensures consistent monthly averages based on the specified date range
  
# Full data range available
data_range:
  start: "2021-01-01"
  end: "2025-12-31"