# Field Mappings Configuration
# Maps raw CSV/PDF field names to normalized field names with traceability

# Configuration metadata and versioning
metadata:
  schema_version: "1.0.0"  # Semantic versioning for schema compatibility
  created_at: "2024-01-01"  # Initial creation date
  description: "Field mappings configuration for ETL pipeline with normalization rules and traceability"

# Default matching and normalization rules
# These settings apply to all mappings unless overridden by specific mapping rules
matching_rules:
  case_sensitive: false          # Whether field name matching is case-sensitive
  trim_whitespace: true          # Remove leading/trailing whitespace from field names
  normalize_diacritics: true     # Convert accented characters to base forms (é → e)
  default_mapping_strategy: "exact"  # Default strategy: exact|fuzzy|regex|contains

# Field mappings organized by data source
mappings:
  sales_mappings:
    # Raw CSV headers → normalized field names
    "Sale Date": "sale_date"
    "Delivery Date": "delivery_date"
    "Return Date": "return_date"
    "Staff Name": "staff_name"
    "Patient Name": "patient_name"
    "Patient ID": "patient_id"
    "Patient ZIP": "patient_zip"
    "Clinic Name": "clinic_name"
    "Referral Source": "referral_source"
    "Subcategory": "subcategory"
    "Ref Description": "ref_description"
    "Campaign": "campaign"
    "Units": "units"
    "Type": "type"
    "Product": "product"
    "Description": "description"
    "S/N": "serial_number"
    "Notes": "notes"
    "Invoice No.": "invoice_no"
    "CPT Code": "cpt_code"
    "Gross Price": "gross_price"
    "Discount": "discount"
    # New flexible discount structure - repeating group
    "discount type 1": "discounts[0].type"
    "discount amount 1": "discounts[0].amount"
    "discount type 2": "discounts[1].type"
    "discount amount 2": "discounts[1].amount"
    "discount type 3": "discounts[2].type"
    "discount amount 3": "discounts[2].amount"
    # Backward compatibility aliases - these will populate discounts[0..2] when present
    "discount_type_1": "discounts[0].type"
    "discount_amount_1": "discounts[0].amount"
    "discount_type_2": "discounts[1].type"
    "discount_amount_2": "discounts[1].amount"
    "discount_type_3": "discounts[2].type"
    "discount_amount_3": "discounts[2].amount"
    "Net Price": "net_price"
    "Sales Tax": "sales_tax"
    "Total Price": "total_price"
    "Receipt Paid": "receipt_paid"

  financial_mappings:
    # P&L line items → normalized field names
    "5017 · Sales": "sales_revenue"
    "5017 · Sales - Other": "sales_revenue_other"
    "Total 5017 · Sales": "total_sales_revenue"
    "Investment Income": "investment_income"
    "Total Revenue": "total_revenue"
    "Salaries": "salaries_expense"
    "Wages": "wages_expense"
    "Rent": "rent_expense"
    "Insurance": "insurance_expense"
    "Utilities": "utilities_expense"
    "Office Supplies": "office_supplies_expense"
    "Marketing": "marketing_expense"
    "Professional Services": "professional_services_expense"
    "Payroll Tax": "payroll_tax_expense"
    "Employee Benefits": "employee_benefits_expense"
    "Equipment": "equipment_expense"
    "Supplies": "supplies_expense"
    "Telephone": "telephone_expense"
    "Travel": "travel_expense"
    "Training": "training_expense"
    "Legal": "legal_expense"
    "Accounting": "accounting_expense"
    "Interest": "interest_expense"
    "Income Tax": "income_tax_expense"
    "Corporate Tax": "corporate_tax_expense"
    "Depreciation": "depreciation_expense"
    "Amortization": "amortization_expense"
    "COGS": "cost_of_goods_sold"
    "Cost of Goods Sold": "cost_of_goods_sold"

  equipment_mappings:
    # Equipment name patterns → normalized names
    "Cello": "cello_audiometer"
    "Trumpet": "trumpet_rem"
    "CL12BLP": "cl12blp_equipment"
    "AUD": "aud_system"
    "Audiometer": "audiometer_system"
    "Test Booth": "test_booth"
    "Hearing Aid": "hearing_aid_equipment"
    "Diagnostic": "diagnostic_equipment"
    "Measurement": "measurement_equipment"

# Field transformation types for traceability
transformation_types:
  "normalize_column_name": "Column name standardization"
  "normalize_date": "Date format standardization"
  "normalize_currency": "Currency value standardization"
  "sum_by_month": "Monthly aggregation"
  "annualize": "Annual projection calculation"
  "equipment_name_mapping": "Equipment name pattern matching"
  "financial_calculation": "Financial metric calculation"
  "direct": "Direct field mapping"
