# Field Mappings Configuration
# Maps raw CSV/PDF field names to normalized field names with traceability

sales_mappings:
  # Raw CSV headers → normalized field names
  "Sale Date": "sale_date"
  "Delivery Date": "delivery_date"
  "Return Date": "return_date"
  "Staff Name": "staff_name"
  "Patient Name": "patient_name"
  "Patient ID": "patient_id"
  "Patient ZIP": "patient_zip"
  "Clinic Name": "clinic_name"
  "Referral Source": "referral_source"
  "Subcategory": "subcategory"
  "Ref Description": "ref_description"
  "Campaign": "campaign"
  "Units": "units"
  "Type": "type"
  "Product": "product"
  "Description": "description"
  "S/N": "serial_number"
  "Notes": "notes"
  "Invoice No.": "invoice_no"
  "CPT Code": "cpt_code"
  "Gross Price": "gross_price"
  "Discount": "discount"
  "Discount Type 1": "discount_type_1"
  "Discount Amount 1": "discount_amount_1"
  "Discount Type 2": "discount_type_2"
  "Discount Amount 2": "discount_amount_2"
  "Discount Type 3": "discount_type_3"
  "Discount Amount 3": "discount_amount_3"
  "Net Price": "net_price"
  "Sales Tax": "sales_tax"
  "Total Price": "total_price"
  "Receipt Paid": "receipt_paid"

financial_mappings:
  # P&L line items → normalized field names
  "5017 · Sales": "sales_revenue"
  "5017 · Sales - Other": "sales_revenue_other"
  "Total 5017 · Sales": "total_sales_revenue"
  "Investment Income": "investment_income"
  "Total Revenue": "total_revenue"
  "Salaries": "salaries_expense"
  "Wages": "wages_expense"
  "Rent": "rent_expense"
  "Insurance": "insurance_expense"
  "Utilities": "utilities_expense"
  "Office Supplies": "office_supplies_expense"
  "Marketing": "marketing_expense"
  "Professional Services": "professional_services_expense"
  "Payroll Tax": "payroll_tax_expense"
  "Employee Benefits": "employee_benefits_expense"
  "Equipment": "equipment_expense"
  "Supplies": "supplies_expense"
  "Telephone": "telephone_expense"
  "Travel": "travel_expense"
  "Training": "training_expense"
  "Legal": "legal_expense"
  "Accounting": "accounting_expense"
  "Interest": "interest_expense"
  "Income Tax": "income_tax_expense"
  "Corporate Tax": "corporate_tax_expense"
  "Depreciation": "depreciation_expense"
  "Amortization": "amortization_expense"
  "COGS": "cost_of_goods_sold"
  "Cost of Goods Sold": "cost_of_goods_sold"

equipment_mappings:
  # Equipment name patterns → normalized names
  "Cello": "cello_audiometer"
  "Trumpet": "trumpet_rem"
  "CL12BLP": "cl12blp_equipment"
  "AUD": "aud_system"
  "Audiometer": "audiometer_system"
  "Test Booth": "test_booth"
  "Hearing Aid": "hearing_aid_equipment"
  "Diagnostic": "diagnostic_equipment"
  "Measurement": "measurement_equipment"

# Field transformation types for traceability
transformation_types:
  "normalize_column_name": "Column name standardization"
  "normalize_date": "Date format standardization"
  "normalize_currency": "Currency value standardization"
  "sum_by_month": "Monthly aggregation"
  "annualize": "Annual projection calculation"
  "equipment_name_mapping": "Equipment name pattern matching"
  "financial_calculation": "Financial metric calculation"
  "direct": "Direct field mapping"
