# Sample Business Rules Configuration
# This is an anonymized version for open source demonstration

locations:
  location_1:
    names: ["Main Office", "Downtown Location"]
    primary: true
    for_sale: true
  location_2:
    names: ["Branch Office", "Suburban Location"]
    primary: false
    for_sale: true
  location_3:
    names: ["Other Location"]
    primary: false
    for_sale: false  # NOT FOR SALE
    
staff_categories:
  audiologists: ["Dr. Smith", "Dr. Johnson", "Dr. Williams"]
  technicians: ["Tech A", "Tech B"]
  support: ["Admin A", "Admin B"]
  
product_categories:
  hearing_aids: ["Hearing Aid", "HA", "Hearing Device"]
  accessories: ["Accessory", "Battery", "Ear Mold"]
  services: ["Service", "Fee", "Consultation"]
  repairs: ["Repair", "Warranty", "Replacement"]
  
financial_metrics:
  ebitda_margin_target: 0.169  # 16.9% target EBITDA margin
  revenue_growth_target: 0.10  # 10% target annual growth
  transaction_volume_target: 1000  # Monthly transaction target
  
valuation_multipliers:
  revenue_multiple_min: 0.8
  revenue_multiple_max: 1.2
  ebitda_multiple_min: 3.0
  ebitda_multiple_max: 5.0
  
data_quality:
  min_transaction_amount: 0.01
  max_transaction_amount: 50000.00
  required_fields: ["sale_date", "total_price", "clinic_name", "staff_name"]
  
# Configurable date range for analysis
analysis_period:
  start_date: "2023-01-01"
  end_date: "2025-06-30"  # End of Q2 2025
  description: "Analysis period: Jan 1, 2023 to end of Q2 2025"
  # Annual projection calculation: (Total Revenue รท Months in Period) ร 12
  
# Full data range available
data_range:
  start: "2021-01-01"
  end: "2025-12-31"

# Configurable equipment value (based on documentation)
equipment:
  total_value: 50000  # Sample equipment value
  description: "Professional audiology equipment including audiometers, REM systems, and diagnostic tools"
  source: "Equipment documentation - sample values"
