# Sample Data Sources Configuration
# This is an anonymized version for open source demonstration

data_sources:
  sales:
    type: csv
    path: "../sample_data/sales_data.csv"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample sales transaction data"
    
  sales_returns:
    type: csv
    path: "../sample_data/sales_returns.csv"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample sales returns data"
    
  sales_exchanges:
    type: csv
    path: "../sample_data/sales_exchanges.csv"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample sales exchanges data"
    
  sales_replacements:
    type: csv
    path: "../sample_data/sales_replacements.csv"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample sales replacements data"
    
  sales_cancelled:
    type: csv
    path: "../sample_data/sales_cancelled.csv"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample cancelled sales data"
    
  sales_conversions:
    type: csv
    path: "../sample_data/sales_conversions.csv"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample sales conversions data"
    
  financial_pnl_2023:
    type: csv
    path: "../sample_data/financial_pnl_2023/"
    pattern: "*.CSV"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample 2023 Profit & Loss statements"
    
  financial_pnl_2024:
    type: csv
    path: "../sample_data/financial_pnl_2024/"
    pattern: "*.CSV"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample 2024 Profit & Loss statements"
    
  financial_balance_sheets:
    type: csv
    path: "../sample_data/financial_balance_sheets/"
    pattern: "*.CSV"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample balance sheet data"
    
  financial_general_ledger:
    type: csv
    path: "../sample_data/financial_general_ledger/"
    pattern: "*.CSV"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample general ledger data"
    
  financial_cogs:
    type: csv
    path: "../sample_data/financial_cogs/"
    pattern: "*.csv"
    encoding: utf-8
    delimiter: ","
    has_header: true
    description: "Sample Cost of Goods Sold data"
    
  equipment_quotes:
    type: pdf
    path: "../sample_data/equipment_quotes/"
    pattern: "*.pdf"
    description: "Sample equipment quote PDFs"
