name = "cranberry-hearing-balance"
compatibility_date = "2025-01-27"
compatibility_flags = ["nodejs_compat"]

# R2 Bucket for OpenNext incremental cache
[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "cranberry-nextjs-cache"

# KV Namespace for OpenNext incremental cache (optional)
[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "1b838f6f51914d8db9ae6c836c374f4e"
