name = "cranberry-auth-worker"
main = "src/index.ts"
compatibility_date = "2025-01-27"
compatibility_flags = ["nodejs_compat"]

# D1 Database configuration
[[d1_databases]]
binding = "cranberry_auth_db"
database_name = "cranberry-auth-db"
database_id = "6e3eab94-840f-484f-900f-a2ddd78196d7"
migrations_dir = "db/migrations"

# R2 Bucket for OpenNext incremental cache
[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "cranberry-nextjs-cache"

# KV Namespace for OpenNext incremental cache (optional)
[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "1b838f6f51914d8db9ae6c836c374f4e"

# Environment variables for default environment (dev/preview)
[vars]
# Non-sensitive public URLs - safe to deploy
NEXT_PUBLIC_APP_URL = "http://localhost:3000"
NEXT_PUBLIC_BETTER_AUTH_URL = "http://localhost:8787"
# BETTER_AUTH_URL needed by Next.js middleware for authentication checks
BETTER_AUTH_URL = "http://localhost:8787"

# Dev/test-only variables moved to .dev.vars or environment-specific sections
# ADMIN_EMAILS - consider moving to env-specific table if it differs by env
# TEST_USER_EMAIL - move to .dev.vars if only used locally
# TEST_USER_PASSWORD - set via .dev.vars locally or wrangler secret put TEST_USER_PASSWORD
# TEST_ADMIN_EMAIL - define only in .dev.vars if needed for local testing
# TEST_ADMIN_PASSWORD - set via .dev.vars locally or wrangler secret put TEST_ADMIN_PASSWORD

# Production environment configuration
[env.production.vars]
BETTER_AUTH_URL = "https://cranberry-auth-worker.paulchrisluke.workers.dev"
NEXT_PUBLIC_APP_URL = "https://cranberry-hearing-balance-workers.paulchrisluke.workers.dev"
NEXT_PUBLIC_BETTER_AUTH_URL = "https://cranberry-auth-worker.paulchrisluke.workers.dev"
# ADMIN_EMAILS - set via wrangler secret put --env production ADMIN_EMAILS

# Secrets (set using: wrangler secret put BETTER_AUTH_SECRET)
# BETTER_AUTH_SECRET - Required for Better Auth
# For local development, use .dev.vars file
