name: Deploy Cranberry Website

on:
  push:
    branches: [ main, master ]
    paths: [ 'website/**', 'etl_pipeline/**', 'data/**', 'docs/**' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'website/**', 'etl_pipeline/**', 'data/**', 'docs/**' ]

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest
    name: Run ETL Pipeline
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ETL Pipeline
      run: |
        echo "Running ETL pipeline for data analysis..."
        python run_pipeline.py
        
    - name: Verify JSON files generated
      run: |
        echo "Checking generated files..."
        ls -la data/final/
        echo "Checking website data directory..."
        ls -la website/src/data/
        
    - name: Upload pipeline artifacts
      uses: actions/upload-artifact@v4
      with:
        name: etl-pipeline-data
        path: |
          data/final/
        retention-days: 7
        if-no-files-found: warn

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Website to Cloudflare Pages
    needs: run-etl-pipeline
    defaults:
      run:
        working-directory: ./website
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download ETL pipeline data
      uses: actions/download-artifact@v4
      with:
        name: etl-pipeline-data
        path: ./public/data/
    
    - name: Set up Python for ETL pipeline
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        cd ..
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ensure data files are available
      run: |
        set -euo pipefail
        echo "Ensuring data files are available for build..."
        ./scripts/ensure-data.sh
    
    - name: Verify website data files
      run: |
        echo "Verifying website data files..."
        ls -la
        echo "Checking if public/data directory exists..."
        if [ ! -d "public/data" ]; then
          echo "ERROR: public/data directory not found"
          exit 1
        fi
        echo "public/data directory exists"
        ls -la public/data/
        echo "Verifying required data files..."
        if [ ! -f "public/data/landing_page_data.json" ]; then
          echo "ERROR: landing_page_data.json not found"
          exit 1
        fi
        echo "Required data files found"
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: website/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Verify data files
      run: |
        echo "Verifying data files are available..."
        ls -la public/data/
        echo "Data files content:"
        head -20 public/data/landing_page_data.json
    
    - name: Build static website
      run: |
        set -euo pipefail
        echo "Current working directory: $(pwd)"
        echo "Listing website directory contents:"
        ls -la
        echo "Listing public directory contents:"
        ls -la public/
        echo "Running static build..."
        npm run build
    
    - name: Deploy to Cloudflare Pages
      if: github.ref == 'refs/heads/main'
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: cranberry-hearing-balance
        directory: ./out
